GET http://localhost:3000/recipes HTTP/1.1

###
GET http://localhost:3000/recipes/3 HTTP/1.1

###
GET http://localhost:3000/technologies HTTP/1.1

###
GET http://localhost:3000/technologies/3 HTTP/1.1

###
GET http://localhost:3000/filter?spiciness=hot&techno_name=css HTTP/1.1
